version: 2.1

orbs:
  python: circleci/python@2.1.2

jobs:
  build:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages: 
            - requirements.txt
      - run:
          name: Run Tests in Parallel
          command: pytest -n auto tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
