version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a Python Docker image
    resource_class: shadabcircle_ci/circleci_shadab  # Specify your self-hosted runner
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest tests/ --junitxml=test-results.xml  # Run tests and generate JUnit report
      - run:
          name: Create Test Results Directory
          command: mkdir -p test-results
      - store_artifacts:
          path: test-results/test-results.xml
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main  # Adjust according to your branch
